include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    avoid_print: warning
    unused_import: warning
    prefer_const_constructors: warning
    prefer_const_literals_to_create_immutables: warning